"""create community/board/role/member/join_request tables

Revision ID: ebeb7105e484
Revises: cd265318ece5
Create Date: 2026-08-19 20:03:41.431428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebeb7105e484'
down_revision: Union[str, Sequence[str], None] = 'cd265318ece5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('allow_post_role_ids', sa.JSON(), nullable=False),
    sa.Column('allow_anonymous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_community_id'), 'boards', ['community_id'], unique=False)
    op.create_table('communities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=False),
    sa.Column('cover_url', sa.String(length=255), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('join_setting', sa.Integer(), nullable=False),
    sa.Column('visitor_interact_switch', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communities_number'), 'communities', ['number'], unique=True)
    op.create_index(op.f('ix_communities_owner_id'), 'communities', ['owner_id'], unique=False)
    op.create_table('join_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('handler_id', sa.BigInteger(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='uq_joinreq_community_user')
    )
    op.create_index(op.f('ix_join_requests_community_id'), 'join_requests', ['community_id'], unique=False)
    op.create_index(op.f('ix_join_requests_user_id'), 'join_requests', ['user_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('member_type', sa.Integer(), nullable=False),
    sa.Column('join_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('join_channel', sa.Integer(), nullable=False),
    sa.Column('shutup_expire_at', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='uq_member_community_user')
    )
    op.create_index(op.f('ix_members_community_id'), 'members', ['community_id'], unique=False)
    op.create_index(op.f('ix_members_user_id'), 'members', ['user_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('community_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('perms', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_community_id'), 'roles', ['community_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_community_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_members_user_id'), table_name='members')
    op.drop_index(op.f('ix_members_community_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_join_requests_user_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_community_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_communities_owner_id'), table_name='communities')
    op.drop_index(op.f('ix_communities_number'), table_name='communities')
    op.drop_table('communities')
    op.drop_index(op.f('ix_boards_community_id'), table_name='boards')
    op.drop_table('boards')
    # ### end Alembic commands ###
